# Generated by Django 4.2.7 on 2025-09-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('financial', 'Financiero'), ('maintenance', 'Mantenimiento'), ('security', 'Seguridad'), ('complaint', 'Queja')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('in_review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
    ]
